#include "CharacterStaticInfo.h"

UCharacterStaticInfo::UCharacterStaticInfo() {
    this->MaxDrawDist = 100000.00f;
    this->PhysicalMaterial = NULL;
    this->BrickPickupCapsuleInflation = 50.00f;
    this->MaxHealth = 1.00f;
    this->MinDamage = 0.00f;
    this->RadialDamageScale = 0.10f;
    this->AutoHealTime = 30.00f;
    this->AutoHealDelay = 10.00f;
    this->BoneDamageGroups.AddDefaulted(1);
    this->RunOverSpeed = 750.00f;
    this->FireDamage = 0.10f;
    this->FireDamageInterval = 1.00f;
    this->AutoExtinguishDelay = 5.00f;
    this->FireEmitter = NULL;
    this->FireSound = NULL;
    this->BoneFlinchMap.AddDefaulted(3);
    this->FlinchAnimationLength = 0.50f;
    this->MinRotationAnimationRate = 45.00f;
    this->LandActionClass = NULL;
    this->MeleeActionClass = NULL;
    this->EyeHeightOffset = -10.00f;
    this->RemoteViewRotationInterpSpeed = 16.00f;
    this->VehicleViewInterpSpeed = 16.00f;
    this->VehicleViewBlendWeight = 0.10f;
    this->VehicleViewDirectionChangeThreshold = 25.00f;
    this->LandedCameraShake = NULL;
    this->WalkFootstepVolume = 0.30f;
    this->WalkFoostepInterval = 0.00f;
    this->SprintFootstepVolume = 0.50f;
    this->CrouchFootstepVolume = 0.20f;
    this->WalkFootstepInterval = 0.45f;
    this->SprintFootstepInterval = 0.32f;
    this->CrouchFootstepInterval = 0.50f;
    this->FoleySoundVolume = 0.50f;
    this->RagdollCollisionSound = NULL;
    this->MinCollisionSoundImpactSpeed = 100.00f;
    this->MinCollisionSoundDelay = 0.50f;
    this->AimInSound = NULL;
    this->AimOutSound = NULL;
    this->IconOffsetZ = 30.00f;
    this->MaxFriendlyIconDrawDist = 20000.00f;
    this->MaxNeutralIconDrawDist = 2000.00f;
    this->MaxHostileIconDrawDist = 200.00f;
    this->InteractionSocketName = TEXT("Spine");
    this->StartSprintTime = 0.75f;
    this->StopSprintTime = 0.40f;
    this->SprintFireThreshold = 0.10f;
    this->AimInTime = 0.30f;
    this->AimOutTime = 0.40f;
    this->AimSoundTimeRatio = 0.20f;
    this->ItemSwayAimScale = 0.80f;
    this->ItemLagInterpSpeed = 24.00f;
    this->ItemLagMaxInputSpeed = 1000.00f;
    this->ItemLagAimScale = 0.50f;
    this->RecoilFalloff = 0.50f;
    this->ItemDropSpeed = 100.00f;
    this->ItemThrowSpeed = 1000.00f;
    this->ExplosiveThrowSpeed = 2000.00f;
    this->ItemThrowAngularSpeedScale = -0.00f;
    this->MaxBrickCarryMass = 100.00f;
    this->BrickCarryDistance = 150.00f;
    this->BrickCarrySpeedCoefficient = 10.00f;
    this->BrickCarryAcceleration = 5000.00f;
    this->BrickThrowSpeed = 150.00f;
}

